name: Deploy ASP.NET to GitHub Pages

on:
  push:
    branches: [ "main" ]   # Runs when you push to main branch
  workflow_dispatch:        # Allows manual triggering

# Grant permissions for GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Set environment variables
env:
  DOTNET_VERSION: '8.0.x'   # Change to '7.0.x' or '6.0.x' if needed

jobs:
  build:
    runs-on: ubuntu-latest  # Uses Ubuntu runner
    steps:
      # Step 1: Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Step 2: Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      # Step 3: Restore NuGet packages
      - name: Restore dependencies
        run: dotnet restore
          
      # Step 4: Publish the project
      - name: Publish project
        run: dotnet publish -c Release -o published --nologo
          
      # Step 5: Upload the built files as artifact
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: published/wwwroot  # This is the crucial path!

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build    # This job depends on the build job completing first
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4